#!/bin/bash

prev=nk

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]] 
		then
			if [[ $cur =~ ^[0-9]+$  ]]
			then
				echo $cur
			else
				echo "Spoiler Aler!"
			fi
			prev=$cur
		fi
	fi
done
